### ISSUE TITLE
Example of Gem Use

### ISSUE THREAD

**Issue by brittanykohler** [gupta-ankit/fitgem_oauth2#2]
Hi,

Do you have an example project that uses this gem? I want to be sure I'm setting everything up correctly in my app.

Thanks,
Brittany

**Comment by brittanykohler** [comment]
I keep getting #<FitgemOauth2::UnauthorizedError: FitgemOauth2::UnauthorizedError> when trying to call any methods-- how can I ensure that I'm setting up the client with the correct information?

**Comment by gupta-ankit** [comment]
Here is a rails application that I wrote just to test the application. It should work

https://github.com/gupta-ankit/FitgemOAuth2Rails

Actually, the constructor here takes more arguments than the original `fitgem`. It expects that you are doing authentication using something like `omniauth-fitbit`.

I will be fixing the constructor to provide appropriate errors instead of failing letter on API call.
